import uuid
from typing import Any

from backend.core.auth import CurrentUser, get_current_user
from backend.core.db import get_db
from backend.models.models import Report
from backend.models.schemas import Report as ReportSchema
from backend.models.schemas import ReportCreate
from backend.workers.tasks import compile_report_task
from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter()


@router.post("", response_model=ReportSchema, status_code=status.HTTP_201_CREATED)
async def generate_report(
    payload: ReportCreate,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
) -> Any:
    """Trigger background compilation of a PDF emissions disclosure report."""
    # Create database record
    report = Report(
        org_id=uuid.UUID(current_user.org_id),
        generated_by=uuid.UUID(current_user.id),
        period_start=payload.period_start,
        period_end=payload.period_end,
        status="pending",
    )
    
    db.add(report)
    await db.commit()
    await db.refresh(report)

    # Queue execution to background worker task
    background_tasks.add_task(compile_report_task, report.id)

    return report


@router.get("", response_model=list[ReportSchema])
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
) -> Any:
    """Fetch all reports generated by the organization."""
    stmt = select(Report).where(
        Report.org_id == uuid.UUID(current_user.org_id)
    ).order_by(Report.created_at.desc())
    
    res = await db.execute(stmt)
    return res.scalars().all()


@router.get("/{report_id}", response_model=ReportSchema)
async def get_report(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
) -> Any:
    """Retrieve details and status of a specific report compilation."""
    stmt = select(Report).where(
        Report.id == report_id,
        Report.org_id == uuid.UUID(current_user.org_id),
    )
    res = await db.execute(stmt)
    report = res.scalars().first()

    if not report:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found or unauthorized",
        )

    return report
